//
// Created by egor on 1/19/24.
//

#include <fstream>

#include "write_vtk.h"

void write_vtk(std::vector<Eigen::Vector3d> const & xs, double r_part, size_t suffix, std::string const & path) {
    std::ofstream ofs(path + "/particles_" + std::to_string(suffix) + ".vtk");

    if (!ofs.good()) {
        throw std::exception();
    }

    ofs << "# vtk DataFile Version 4.0\n";
    ofs << "Generated by libtimestep\n";
    ofs << "ASCII\n";
    ofs << "DATASET POLYDATA\n";
    ofs << "POINTS " << xs.size() << " FLOAT\n";

    // Coordin ates are normalized to avoid issues with ParaView and small particles
    for (auto const & p : xs) {
        ofs << p[0] / r_part << " " << p[1] / r_part << " " << p[2] / r_part << " ";
    }

    ofs << "\n" << std::endl;
}
