name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout-and-ctest-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt install libtbb2-dev
      - run: dpkg -L libtbb2-dev
      - name: Run unit tests
        uses: HorstBaerbel/action-ctest@1.1
